import Foundation
import StockPlanShared

public struct RatiosTTMResponse: Codable, Sendable, Equatable {
    public let symbol: String
    public let grossProfitMarginTTM: Double?
    public let ebitMarginTTM: Double?
    public let ebitdaMarginTTM: Double?
    public let operatingProfitMarginTTM: Double?
    public let pretaxProfitMarginTTM: Double?
    public let continuousOperationsProfitMarginTTM: Double?
    public let netProfitMarginTTM: Double?
    public let bottomLineProfitMarginTTM: Double?
    public let receivablesTurnoverTTM: Double?
    public let payablesTurnoverTTM: Double?
    public let inventoryTurnoverTTM: Double?
    public let fixedAssetTurnoverTTM: Double?
    public let assetTurnoverTTM: Double?
    public let currentRatioTTM: Double?
    public let quickRatioTTM: Double?
    public let solvencyRatioTTM: Double?
    public let cashRatioTTM: Double?
    public let priceToEarningsRatioTTM: Double?
    public let priceToEarningsGrowthRatioTTM: Double?
    public let forwardPriceToEarningsGrowthRatioTTM: Double?
    public let priceToBookRatioTTM: Double?
    public let priceToSalesRatioTTM: Double?
    public let priceToFreeCashFlowRatioTTM: Double?
    public let priceToOperatingCashFlowRatioTTM: Double?
    public let debtToAssetsRatioTTM: Double?
    public let debtToEquityRatioTTM: Double?
    public let debtToCapitalRatioTTM: Double?
    public let longTermDebtToCapitalRatioTTM: Double?
    public let financialLeverageRatioTTM: Double?
    public let workingCapitalTurnoverRatioTTM: Double?
    public let operatingCashFlowRatioTTM: Double?
    public let operatingCashFlowSalesRatioTTM: Double?
    public let freeCashFlowOperatingCashFlowRatioTTM: Double?
    public let debtServiceCoverageRatioTTM: Double?
    public let interestCoverageRatioTTM: Double?
    public let shortTermOperatingCashFlowCoverageRatioTTM: Double?
    public let operatingCashFlowCoverageRatioTTM: Double?
    public let capitalExpenditureCoverageRatioTTM: Double?
    public let dividendPaidAndCapexCoverageRatioTTM: Double?
    public let dividendPayoutRatioTTM: Double?
    public let dividendYieldTTM: Double?
    public let enterpriseValueTTM: Double?
    public let revenuePerShareTTM: Double?
    public let netIncomePerShareTTM: Double?
    public let interestDebtPerShareTTM: Double?
    public let cashPerShareTTM: Double?
    public let bookValuePerShareTTM: Double?
    public let tangibleBookValuePerShareTTM: Double?
    public let shareholdersEquityPerShareTTM: Double?
    public let operatingCashFlowPerShareTTM: Double?
    public let capexPerShareTTM: Double?
    public let freeCashFlowPerShareTTM: Double?
    public let netIncomePerEBTTTM: Double?
    public let ebtPerEbitTTM: Double?
    public let priceToFairValueTTM: Double?
    public let debtToMarketCapTTM: Double?
    public let effectiveTaxRateTTM: Double?
    public let enterpriseValueMultipleTTM: Double?
}

public struct BalanceSheetStatementResponse: Codable, Sendable, Equatable {
    public let date: String
    public let symbol: String
    public let reportedCurrency: String?
    public let cik: String?
    public let filingDate: String?
    public let acceptedDate: String?
    public let fiscalYear: String?
    public let period: String?
    public let cashAndCashEquivalents: Double?
    public let shortTermInvestments: Double?
    public let cashAndShortTermInvestments: Double?
    public let netReceivables: Double?
    public let accountsReceivables: Double?
    public let otherReceivables: Double?
    public let inventory: Double?
    public let prepaids: Double?
    public let otherCurrentAssets: Double?
    public let totalCurrentAssets: Double?
    public let propertyPlantEquipmentNet: Double?
    public let goodwill: Double?
    public let intangibleAssets: Double?
    public let goodwillAndIntangibleAssets: Double?
    public let longTermInvestments: Double?
    public let taxAssets: Double?
    public let otherNonCurrentAssets: Double?
    public let totalNonCurrentAssets: Double?
    public let otherAssets: Double?
    public let totalAssets: Double?
    public let totalPayables: Double?
    public let accountPayables: Double?
    public let otherPayables: Double?
    public let accruedExpenses: Double?
    public let shortTermDebt: Double?
    public let capitalLeaseObligationsCurrent: Double?
    public let taxPayables: Double?
    public let deferredRevenue: Double?
    public let otherCurrentLiabilities: Double?
    public let totalCurrentLiabilities: Double?
    public let longTermDebt: Double?
    public let deferredRevenueNonCurrent: Double?
    public let deferredTaxLiabilitiesNonCurrent: Double?
    public let otherNonCurrentLiabilities: Double?
    public let totalNonCurrentLiabilities: Double?
    public let otherLiabilities: Double?
    public let capitalLeaseObligations: Double?
    public let totalLiabilities: Double?
    public let treasuryStock: Double?
    public let preferredStock: Double?
    public let commonStock: Double?
    public let retainedEarnings: Double?
    public let additionalPaidInCapital: Double?
    public let accumulatedOtherComprehensiveIncomeLoss: Double?
    public let otherTotalStockholdersEquity: Double?
    public let totalStockholdersEquity: Double?
    public let totalEquity: Double?
    public let minorityInterest: Double?
    public let totalLiabilitiesAndTotalEquity: Double?
    public let totalInvestments: Double?
    public let totalDebt: Double?
    public let netDebt: Double?
}

public struct CashFlowStatementResponse: Codable, Sendable, Equatable {
    public let date: String
    public let symbol: String
    public let reportedCurrency: String?
    public let cik: String?
    public let filingDate: String?
    public let acceptedDate: String?
    public let fiscalYear: String?
    public let period: String?
    public let netIncome: Double?
    public let depreciationAndAmortization: Double?
    public let deferredIncomeTax: Double?
    public let stockBasedCompensation: Double?
    public let changeInWorkingCapital: Double?
    public let accountsReceivables: Double?
    public let inventory: Double?
    public let accountsPayables: Double?
    public let otherWorkingCapital: Double?
    public let otherNonCashItems: Double?
    public let netCashProvidedByOperatingActivities: Double?
    public let investmentsInPropertyPlantAndEquipment: Double?
    public let acquisitionsNet: Double?
    public let purchasesOfInvestments: Double?
    public let salesMaturitiesOfInvestments: Double?
    public let otherInvestingActivities: Double?
    public let netCashProvidedByInvestingActivities: Double?
    public let netDebtIssuance: Double?
    public let longTermNetDebtIssuance: Double?
    public let shortTermNetDebtIssuance: Double?
    public let netStockIssuance: Double?
    public let netCommonStockIssuance: Double?
    public let commonStockIssuance: Double?
    public let commonStockRepurchased: Double?
    public let netPreferredStockIssuance: Double?
    public let netDividendsPaid: Double?
    public let commonDividendsPaid: Double?
    public let preferredDividendsPaid: Double?
    public let otherFinancingActivities: Double?
    public let netCashProvidedByFinancingActivities: Double?
    public let effectOfForexChangesOnCash: Double?
    public let netChangeInCash: Double?
    public let cashAtEndOfPeriod: Double?
    public let cashAtBeginningOfPeriod: Double?
    public let operatingCashFlow: Double?
    public let capitalExpenditure: Double?
    public let freeCashFlow: Double?
    public let incomeTaxesPaid: Double?
    public let interestPaid: Double?
}

public struct FinancialGrowthResponse: Codable, Sendable, Equatable {
    public let symbol: String
    public let date: String
    public let fiscalYear: String?
    public let period: String?
    public let reportedCurrency: String?
    public let revenueGrowth: Double?
    public let grossProfitGrowth: Double?
    public let ebitgrowth: Double?
    public let operatingIncomeGrowth: Double?
    public let netIncomeGrowth: Double?
    public let epsgrowth: Double?
    public let epsdilutedGrowth: Double?
    public let weightedAverageSharesGrowth: Double?
    public let weightedAverageSharesDilutedGrowth: Double?
    public let dividendsPerShareGrowth: Double?
    public let operatingCashFlowGrowth: Double?
    public let receivablesGrowth: Double?
    public let inventoryGrowth: Double?
    public let assetGrowth: Double?
    public let bookValueperShareGrowth: Double?
    public let debtGrowth: Double?
    public let rdexpenseGrowth: Double?
    public let sgaexpensesGrowth: Double?
    public let freeCashFlowGrowth: Double?
    public let tenYRevenueGrowthPerShare: Double?
    public let fiveYRevenueGrowthPerShare: Double?
    public let threeYRevenueGrowthPerShare: Double?
    public let tenYOperatingCFGrowthPerShare: Double?
    public let fiveYOperatingCFGrowthPerShare: Double?
    public let threeYOperatingCFGrowthPerShare: Double?
    public let tenYNetIncomeGrowthPerShare: Double?
    public let fiveYNetIncomeGrowthPerShare: Double?
    public let threeYNetIncomeGrowthPerShare: Double?
    public let tenYShareholdersEquityGrowthPerShare: Double?
    public let fiveYShareholdersEquityGrowthPerShare: Double?
    public let threeYShareholdersEquityGrowthPerShare: Double?
    public let tenYDividendperShareGrowthPerShare: Double?
    public let fiveYDividendperShareGrowthPerShare: Double?
    public let threeYDividendperShareGrowthPerShare: Double?
    public let ebitdaGrowth: Double?
    public let growthCapitalExpenditure: Double?
    public let tenYBottomLineNetIncomeGrowthPerShare: Double?
    public let fiveYBottomLineNetIncomeGrowthPerShare: Double?
    public let threeYBottomLineNetIncomeGrowthPerShare: Double?
}

public struct AnalystEstimatesResponse: Codable, Sendable, Equatable {
    public let symbol: String
    public let date: String
    public let revenueLow: Double?
    public let revenueHigh: Double?
    public let revenueAvg: Double?
    public let ebitdaLow: Double?
    public let ebitdaHigh: Double?
    public let ebitdaAvg: Double?
    public let ebitLow: Double?
    public let ebitHigh: Double?
    public let ebitAvg: Double?
    public let netIncomeLow: Double?
    public let netIncomeHigh: Double?
    public let netIncomeAvg: Double?
    public let sgaExpenseLow: Double?
    public let sgaExpenseHigh: Double?
    public let sgaExpenseAvg: Double?
    public let epsAvg: Double?
    public let epsHigh: Double?
    public let epsLow: Double?
    public let numAnalystsRevenue: Int?
    public let numAnalystsEps: Int?
}

public struct RatiosResponse: Codable, Sendable, Equatable {
    public let symbol: String
    public let date: String
    public let fiscalYear: String?
    public let period: String?
    public let reportedCurrency: String?
    public let grossProfitMargin: Double?
    public let ebitMargin: Double?
    public let ebitdaMargin: Double?
    public let operatingProfitMargin: Double?
    public let pretaxProfitMargin: Double?
    public let continuousOperationsProfitMargin: Double?
    public let netProfitMargin: Double?
    public let bottomLineProfitMargin: Double?
    public let receivablesTurnover: Double?
    public let payablesTurnover: Double?
    public let inventoryTurnover: Double?
    public let fixedAssetTurnover: Double?
    public let assetTurnover: Double?
    public let currentRatio: Double?
    public let quickRatio: Double?
    public let solvencyRatio: Double?
    public let cashRatio: Double?
    public let priceToEarningsRatio: Double?
    public let priceToEarningsGrowthRatio: Double?
    public let forwardPriceToEarningsGrowthRatio: Double?
    public let priceToBookRatio: Double?
    public let priceToSalesRatio: Double?
    public let priceToFreeCashFlowRatio: Double?
    public let priceToOperatingCashFlowRatio: Double?
    public let debtToAssetsRatio: Double?
    public let debtToEquityRatio: Double?
    public let debtToCapitalRatio: Double?
    public let longTermDebtToCapitalRatio: Double?
    public let financialLeverageRatio: Double?
    public let workingCapitalTurnoverRatio: Double?
    public let operatingCashFlowRatio: Double?
    public let operatingCashFlowSalesRatio: Double?
    public let freeCashFlowOperatingCashFlowRatio: Double?
    public let debtServiceCoverageRatio: Double?
    public let interestCoverageRatio: Double?
    public let shortTermOperatingCashFlowCoverageRatio: Double?
    public let operatingCashFlowCoverageRatio: Double?
    public let capitalExpenditureCoverageRatio: Double?
    public let dividendPaidAndCapexCoverageRatio: Double?
    public let dividendPayoutRatio: Double?
    public let dividendYield: Double?
    public let dividendYieldPercentage: Double?
    public let revenuePerShare: Double?
    public let netIncomePerShare: Double?
    public let interestDebtPerShare: Double?
    public let cashPerShare: Double?
    public let bookValuePerShare: Double?
    public let tangibleBookValuePerShare: Double?
    public let shareholdersEquityPerShare: Double?
    public let operatingCashFlowPerShare: Double?
    public let capexPerShare: Double?
    public let freeCashFlowPerShare: Double?
    public let netIncomePerEBT: Double?
    public let ebtPerEbit: Double?
    public let priceToFairValue: Double?
    public let debtToMarketCap: Double?
    public let effectiveTaxRate: Double?
    public let enterpriseValueMultiple: Double?
}
